import Foundation

/// Colors supported by PlantUML, see https://github.com/qywx/PlantUML-colors/blob/master/plantuml-colors-table.puml
public enum Color: String, CaseIterable, Codable {
    /// AliceBlue
    case AliceBlue
    /// AntiqueWhite
    case AntiqueWhite
    /// Aqua
    case Aqua
    /// Aquamarine
    case Aquamarine
    /// Azure
    case Azure
    /// Beige
    case Beige
    /// Bisque
    case Bisque
    /// Black
    case Black
    /// BlanchedAlmond
    case BlanchedAlmond
    /// Blue
    case Blue
    /// BlueViolet
    case BlueViolet
    /// Brown
    case Brown
    /// BurlyWood
    case BurlyWood
    /// CadetBlue
    case CadetBlue
    /// Chartreuse
    case Chartreuse
    /// Chocolate
    case Chocolate
    /// Coral
    case Coral
    /// CornflowerBlue
    case CornflowerBlue
    /// Cornsilk
    case Cornsilk
    /// Crimson
    case Crimson
    /// Cyan
    case Cyan
    /// DarkBlue
    case DarkBlue
    /// DarkCyan
    case DarkCyan
    /// DarkGoldenRod
    case DarkGoldenRod
    /// DarkGray
    case DarkGray
    /// DarkGreen
    case DarkGreen
    /// DarkGrey
    case DarkGrey
    /// DarkKhaki
    case DarkKhaki
    /// DarkMagenta
    case DarkMagenta
    /// DarkOliveGreen
    case DarkOliveGreen
    /// DarkOrchid
    case DarkOrchid
    /// DarkRed
    case DarkRed
    /// DarkSalmon
    case DarkSalmon
    /// DarkSeaGreen
    case DarkSeaGreen
    /// DarkSlateBlue
    case DarkSlateBlue
    /// DarkSlateGray
    case DarkSlateGray
    /// DarkSlateGrey
    case DarkSlateGrey
    /// DarkTurquoise
    case DarkTurquoise
    /// DarkViolet
    case DarkViolet
    /// Darkorange
    case Darkorange
    /// DeepPink
    case DeepPink
    /// DeepSkyBlue
    case DeepSkyBlue
    /// DimGray
    case DimGray
    /// DimGrey
    case DimGrey
    /// DodgerBlue
    case DodgerBlue
    /// FireBrick
    case FireBrick
    /// FloralWhite
    case FloralWhite
    /// ForestGreen
    case ForestGreen
    /// Fuchsia
    case Fuchsia
    /// Gainsboro
    case Gainsboro
    /// GhostWhite
    case GhostWhite
    /// Gold
    case Gold
    /// GoldenRod
    case GoldenRod
    /// Gray
    case Gray
    /// Green
    case Green
    /// GreenYellow
    case GreenYellow
    /// Grey
    case Grey
    /// HoneyDew
    case HoneyDew
    /// HotPink
    case HotPink
    /// IndianRed
    case IndianRed
    /// Indigo
    case Indigo
    /// Ivory
    case Ivory
    /// Khaki
    case Khaki
    /// Lavender
    case Lavender
    /// LavenderBlush
    case LavenderBlush
    /// LawnGreen
    case LawnGreen
    /// LemonChiffon
    case LemonChiffon
    /// LightBlue
    case LightBlue
    /// LightCoral
    case LightCoral
    /// LightCyan
    case LightCyan
    /// LightGoldenRodYellow
    case LightGoldenRodYellow
    /// LightGray
    case LightGray
    /// LightGreen
    case LightGreen
    /// LightGrey
    case LightGrey
    /// LightPink
    case LightPink
    /// LightSalmon
    case LightSalmon
    /// LightSeaGreen
    case LightSeaGreen
    /// LightSkyBlue
    case LightSkyBlue
    /// LightSlateGray
    case LightSlateGray
    /// LightSlateGrey
    case LightSlateGrey
    /// LightSteelBlue
    case LightSteelBlue
    /// LightYellow
    case LightYellow
    /// Lime
    case Lime
    /// LimeGreen
    case LimeGreen
    /// Linen
    case Linen
    /// Magenta
    case Magenta
    /// Maroon
    case Maroon
    /// MediumAquaMarine
    case MediumAquaMarine
    /// MediumBlue
    case MediumBlue
    /// MediumOrchid
    case MediumOrchid
    /// MediumPurple
    case MediumPurple
    /// MediumSeaGreen
    case MediumSeaGreen
    /// MediumSlateBlue
    case MediumSlateBlue
    /// MediumSpringGreen
    case MediumSpringGreen
    /// MediumTurquoise
    case MediumTurquoise
    /// MediumVioletRed
    case MediumVioletRed
    /// MidnightBlue
    case MidnightBlue
    /// MintCream
    case MintCream
    /// MistyRose
    case MistyRose
    /// Moccasin
    case Moccasin
    /// NavajoWhite
    case NavajoWhite
    /// Navy
    case Navy
    /// OldLace
    case OldLace
    /// Olive
    case Olive
    /// OliveDrab
    case OliveDrab
    /// Orange
    case Orange
    /// OrangeRed
    case OrangeRed
    /// Orchid
    case Orchid
    /// PaleGoldenRod
    case PaleGoldenRod
    /// PaleGreen
    case PaleGreen
    /// PaleTurquoise
    case PaleTurquoise
    /// PaleVioletRed
    case PaleVioletRed
    /// PapayaWhip
    case PapayaWhip
    /// PeachPuff
    case PeachPuff
    /// Peru
    case Peru
    /// Pink
    case Pink
    /// Plum
    case Plum
    /// PowderBlue
    case PowderBlue
    /// Purple
    case Purple
    /// Red
    case Red
    /// RosyBrown
    case RosyBrown
    /// RoyalBlue
    case RoyalBlue
    /// SaddleBrown
    case SaddleBrown
    /// Salmon
    case Salmon
    /// SandyBrown
    case SandyBrown
    /// SeaGreen
    case SeaGreen
    /// SeaShell
    case SeaShell
    /// Sienna
    case Sienna
    /// Silver
    case Silver
    /// SkyBlue
    case SkyBlue
    /// SlateBlue
    case SlateBlue
    /// SlateGray
    case SlateGray
    /// SlateGrey
    case SlateGrey
    /// Snow
    case Snow
    /// SpringGreen
    case SpringGreen
    /// SteelBlue
    case SteelBlue
    /// Tan
    case Tan
    /// Teal
    case Teal
    /// Thistle
    case Thistle
    /// Tomato
    case Tomato
    /// Turquoise
    case Turquoise
    /// Violet
    case Violet
    /// Wheat
    case Wheat
    /// White
    case White
    /// WhiteSmoke
    case WhiteSmoke
    /// Yellow
    case Yellow
    /// YellowGreen
    case YellowGreen
}
