files:
  include:
  - "Sources/SwiftPlantUMLFramework/**/*.swift"
  exclude:
  - "Tests/**/*.swift"
elements:
  havingAccessLevel:
  - public
  showMembersWithAccessLevel:
  - public
  - internal
  - private
  showGenerics: true
  showNestedTypes: false
  showExtensions: merged
  mergedExtensionMemberIndicator: "!!!"
  showMemberAccessLevelAttribute: true
  exclude:
  - Logger
  - LogLevel
hideShowCommands:
- hide empty members
skinparamCommands:
- skinparam sequenceMessageAlign center ## just an example; this will have no impact to a class diagram
#includeRemoteURL: https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/hacker/puml-theme-hacker.puml
theme: hacker
relationships:
  inheritance:
    label: "inherits from"
    style:
      lineStyle: dotted
      lineColor: DarkViolet
      textColor: DarkViolet
    exclude:
    - "Codable"
  realize:
    label: "conforms to"
    style:
      lineStyle: dashed
      lineColor: Blue
      textColor: Blue
  dependency:
    label: extends
    style:
      lineStyle: bold
      lineColor: DarkGreen
      textColor: DarkViolet
stereotypes:
  class:
    name: class
    spot:
      character: C
      color: AliceBlue
  struct:
    spot:
      character: S
      color: AntiqueWhite
  extension:
    spot:
      character: X
      color: AntiqueWhite
  enum:
    spot:
      character: E
      color: AntiqueWhite
  protocol:
    spot:
      character: P
      color: AntiqueWhite
texts:
  header: Simple header example
  title: |
    <u>Formatted</u> title example
    on <i>several</i> lines and using <font color=red>html</font>
  legend: Some boxed text
  caption: Second to last
  footer: The end